[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools"]

[tool.ruff]
line-length = 80
indent-width = 2

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
